"""empty message

Revision ID: 7095840de5a0
Revises: 
Create Date: 2026-09-16 01:03:09.150820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7095840de5a0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_training_stats',
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('line_analytic_version', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('fails', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('target_interval', sa.Interval(), nullable=False),
    sa.CheckConstraint("target_interval > INTERVAL '0 seconds'", name='ck_line_training_stats_target_interval_positive'),
    sa.CheckConstraint('attempts >= 0', name='ck_line_training_stats_attempts_non_negative'),
    sa.CheckConstraint('consecutive_failures >= 0', name='ck_line_training_stats_failure_streak_non_negative'),
    sa.CheckConstraint('consecutive_successes >= 0', name='ck_line_training_stats_success_streak_non_negative'),
    sa.CheckConstraint('fails <= attempts', name='ck_line_training_stats_fails_lte_attempts'),
    sa.CheckConstraint('fails >= 0', name='ck_line_training_stats_fails_non_negative'),
    sa.CheckConstraint('line_analytic_version >= 1', name='ck_line_training_stats_analytic_version_positive'),
    sa.PrimaryKeyConstraint('line_id', 'line_analytic_version')
    )
    op.create_table('training_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repertoire_id', sa.UUID(), nullable=False),
    sa.Column('start_line_id', sa.UUID(), nullable=False),
    sa.Column('current_ply', sa.Integer(), nullable=False),
    sa.Column('repertoire_revision', sa.Integer(), nullable=False),
    sa.Column('selected_moves', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('selected_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PASSED', 'FAILED', 'INVALIDATED', name='training_session_status'), nullable=False),
    sa.Column('error_line_id', sa.UUID(), nullable=True),
    sa.Column('error_line_analytic_version', sa.Integer(), nullable=True),
    sa.Column('error_ply', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('current_ply >= 0', name='ck_training_sessions_current_ply_non_negative'),
    sa.CheckConstraint('error_ply >= 0', name='ck_training_sessions_error_ply_non_negative'),
    sa.CheckConstraint('repertoire_revision >= 0', name='ck_training_sessions_revision_non_negative'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_sessions')
    op.drop_table('line_training_stats')
    # ### end Alembic commands ###
