"""create training tables

Revision ID: ecbe4cb1c2e7
Revises: 
Create Date: 2026-10-03 15:18:01.447039

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecbe4cb1c2e7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('line_training_stats',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('line_id', sa.UUID(), nullable=False),
    sa.Column('line_analytic_version', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('fails', sa.Integer(), nullable=False),
    sa.Column('consecutive_successes', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('target_interval', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name='line_training_stats_attempts_check'),
    sa.CheckConstraint('consecutive_failures >= 0', name='line_training_stats_failure_streak_check'),
    sa.CheckConstraint('consecutive_successes >= 0', name='line_training_stats_success_streak_check'),
    sa.CheckConstraint('fails <= attempts', name='line_training_stats_fails_attempts_check'),
    sa.CheckConstraint('fails >= 0', name='line_training_stats_fails_check'),
    sa.CheckConstraint('line_analytic_version >= 1', name='line_training_stats_version_check'),
    sa.CheckConstraint('target_interval > 0', name='line_training_stats_target_interval_check'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'line_id', 'line_analytic_version', name='uq_line_training_stats_user_line_version')
    )
    op.create_index(op.f('ix_line_training_stats_line_id'), 'line_training_stats', ['line_id'], unique=False)
    op.create_index(op.f('ix_line_training_stats_user_id'), 'line_training_stats', ['user_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repertoire_id', sa.UUID(), nullable=False),
    sa.Column('start_line_id', sa.UUID(), nullable=False),
    sa.Column('current_ply', sa.Integer(), nullable=False),
    sa.Column('repertoire_revision', sa.Integer(), nullable=False),
    sa.Column('selected_moves', postgresql.ARRAY(sa.Text()), nullable=False),
    sa.Column('selected_path', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PASSED', 'FAILED', 'INVALIDATED', name='training_session_status'), nullable=False),
    sa.Column('error_line_id', sa.UUID(), nullable=True),
    sa.Column('error_line_analytic_version', sa.Integer(), nullable=True),
    sa.Column('error_ply', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('current_ply >= 0', name='training_sessions_current_ply_check'),
    sa.CheckConstraint('error_ply >= 0', name='training_sessions_error_ply_check'),
    sa.CheckConstraint('repertoire_revision >= 0', name='training_sessions_repertoire_revision_check'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_repertoire_id'), 'training_sessions', ['repertoire_id'], unique=False)
    op.create_index('ix_training_sessions_user_created_at', 'training_sessions', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index('ix_training_sessions_user_created_at', table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_repertoire_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_line_training_stats_user_id'), table_name='line_training_stats')
    op.drop_index(op.f('ix_line_training_stats_line_id'), table_name='line_training_stats')
    op.drop_table('line_training_stats')
    # ### end Alembic commands ###
