repos:
  - repo: local
    hooks:
      # Auth
      - id: auth-ruff-check-fix
        name: Auth Ruff check --fix
        entry: uv run --directory backend/auth ruff check --fix
        language: system
        types: [python]
        pass_filenames: false

      - id: auth-ruff-format
        name: Auth Ruff format
        entry: uv run --directory backend/auth ruff format
        language: system
        types: [python]
        pass_filenames: false

      - id: auth-ruff-check
        name: Auth Ruff check
        entry: uv run --directory backend/auth ruff check
        language: system
        types: [python]
        pass_filenames: false

      - id: auth-mypy
        name: Auth Mypy
        entry: uv run --directory backend/auth mypy .
        language: system
        pass_filenames: false

      # Email Sender
      - id: email-sender-ruff-check-fix
        name: Email Sender Ruff check --fix
        entry: uv run --directory backend/email_sender ruff check --fix
        language: system
        types: [python]
        pass_filenames: false

      - id: email-sender-ruff-format
        name: Email Sender Ruff format
        entry: uv run --directory backend/email_sender ruff format
        language: system
        types: [python]
        pass_filenames: false

      - id: email-sender-ruff-check
        name: Email Sender Ruff check
        entry: uv run --directory backend/email_sender ruff check
        language: system
        types: [python]
        pass_filenames: false

      - id: email-sender-mypy
        name: Email Sender Mypy
        entry: uv run --directory backend/email_sender mypy .
        language: system
        pass_filenames: false
