"""implement-not-empty-moves

Revision ID: 4bf7fc24092d
Revises: 576bc21be91a
Create Date: 2026-09-04 13:49:48.872906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4bf7fc24092d'
down_revision: Union[str, Sequence[str], None] = '576bc21be91a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_lines_moves_not_empty', 'lines', 'cardinality(moves) > 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_lines_moves_not_empty', 'lines', type_='check')
    # ### end Alembic commands ###
