"""implement-race-safety

Revision ID: 576bc21be91a
Revises: 8a5ea231e596
Create Date: 2026-09-04 13:26:07.229168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from core.constants import (
    LINES_REPERTOIRE_PARENT_FK,
    LINES_MOVES_CHECK_CONSTRAINT,
    UNIQUE_ROOT_CONSTRAINT,
)


# revision identifiers, used by Alembic.
revision: str = '576bc21be91a'
down_revision: Union[str, Sequence[str], None] = '8a5ea231e596'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_lines_repertoire_id', 'lines', ['repertoire_id', 'id'])
    op.drop_constraint(op.f('lines_parent_id_fkey'), 'lines', type_='foreignkey')
    op.create_foreign_key('fk_lines_repertoire_parent', 'lines', 'lines', ['repertoire_id', 'parent_id'], ['repertoire_id', 'id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_lines_repertoire_parent', 'lines', type_='foreignkey')
    op.create_foreign_key(op.f('lines_parent_id_fkey'), 'lines', 'lines', ['parent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_lines_repertoire_id', 'lines', type_='unique')
    # ### end Alembic commands ###
