"""create repertoires tables

Revision ID: 8a5ea231e596
Revises: 
Create Date: 2026-09-04 12:59:05.290558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a5ea231e596'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repertoires',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('side', sa.Enum('white', 'black', name='repertoire_side'), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repertoires_user_id'), 'repertoires', ['user_id'], unique=False)
    op.create_table('lines',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repertoire_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('tag', sa.String(length=100), nullable=True),
    sa.Column('moves', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lines_parent_id'), 'lines', ['parent_id'], unique=False)
    op.create_index(op.f('ix_lines_repertoire_id'), 'lines', ['repertoire_id'], unique=False)
    op.create_index('uq_lines_repertoire_root', 'lines', ['repertoire_id'], unique=True, postgresql_where=sa.text('parent_id IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_lines_repertoire_root', table_name='lines', postgresql_where=sa.text('parent_id IS NULL'))
    op.drop_index(op.f('ix_lines_repertoire_id'), table_name='lines')
    op.drop_index(op.f('ix_lines_parent_id'), table_name='lines')
    op.drop_table('lines')
    op.drop_index(op.f('ix_repertoires_user_id'), table_name='repertoires')
    op.drop_table('repertoires')
    # ### end Alembic commands ###
