"""empty message

Revision ID: e571beed1f2d
Revises: 4aff27c2da3a
Create Date: 2026-09-07 12:04:20.316839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e571beed1f2d'
down_revision: Union[str, Sequence[str], None] = '4aff27c2da3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lines', sa.Column('parent_analytic_version', sa.Integer(), nullable=True))
    op.drop_column('repertoires', 'analytic_version')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repertoires', sa.Column('analytic_version', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('lines', 'parent_analytic_version')
    # ### end Alembic commands ###
