# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_gen.repertoire.v1 import repertoire_pb2 as grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2

GRPC_GENERATED_VERSION = '1.84.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_gen/repertoire/v1/repertoire_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RepertoireServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTrainingTree = channel.unary_unary(
                '/repertoire.v1.RepertoireService/GetTrainingTree',
                request_serializer=grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetTrainingTreeRequest.SerializeToString, # type: ignore
                response_deserializer=grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetTrainingTreeResponse.FromString, # type: ignore
                _registered_method=True)
        self.GetRepertoireRevision = channel.unary_unary(
                '/repertoire.v1.RepertoireService/GetRepertoireRevision',
                request_serializer=grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetRepertoireRevisionRequest.SerializeToString, # type: ignore
                response_deserializer=grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetRepertoireRevisionResponse.FromString, # type: ignore
                _registered_method=True)


class RepertoireServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetTrainingTree(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRepertoireRevision(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RepertoireServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTrainingTree': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTrainingTree,
                    request_deserializer=grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetTrainingTreeRequest.FromString, # type: ignore
                    response_serializer=grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetTrainingTreeResponse.SerializeToString, # type: ignore
            ),
            'GetRepertoireRevision': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRepertoireRevision,
                    request_deserializer=grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetRepertoireRevisionRequest.FromString, # type: ignore
                    response_serializer=grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetRepertoireRevisionResponse.SerializeToString, # type: ignore
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'repertoire.v1.RepertoireService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('repertoire.v1.RepertoireService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RepertoireService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTrainingTree(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/repertoire.v1.RepertoireService/GetTrainingTree',
            grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetTrainingTreeRequest.SerializeToString, # type: ignore
            grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetTrainingTreeResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRepertoireRevision(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/repertoire.v1.RepertoireService/GetRepertoireRevision',
            grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetRepertoireRevisionRequest.SerializeToString, # type: ignore
            grpc__gen_dot_repertoire_dot_v1_dot_repertoire__pb2.GetRepertoireRevisionResponse.FromString, # type: ignore
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
