# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc_gen/repertoire/v1/repertoire.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'grpc_gen/repertoire/v1/repertoire.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'grpc_gen/repertoire/v1/repertoire.proto\x12\rrepertoire.v1\"W\n\x16GetTrainingTreeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rrepertoire_id\x18\x02 \x01(\t\x12\x15\n\rstart_line_id\x18\x03 \x01(\t\"b\n\x17GetTrainingTreeResponse\x12\x1b\n\x13repertoire_revision\x18\x01 \x01(\x05\x12*\n\x05lines\x18\x02 \x03(\x0b\x32\x1b.repertoire.v1.TrainingLine\"c\n\x0cTrainingLine\x12\n\n\x02id\x18\x01 \x01(\t\x12\x11\n\tparent_id\x18\x02 \x01(\t\x12\x0b\n\x03tag\x18\x03 \x01(\t\x12\r\n\x05moves\x18\x04 \x03(\t\x12\x18\n\x10\x61nalytic_version\x18\x05 \x01(\x05\"F\n\x1cGetRepertoireRevisionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x15\n\rrepertoire_id\x18\x02 \x01(\t\"<\n\x1dGetRepertoireRevisionResponse\x12\x1b\n\x13repertoire_revision\x18\x01 \x01(\x05\x32\xe9\x01\n\x11RepertoireService\x12`\n\x0fGetTrainingTree\x12%.repertoire.v1.GetTrainingTreeRequest\x1a&.repertoire.v1.GetTrainingTreeResponse\x12r\n\x15GetRepertoireRevision\x12+.repertoire.v1.GetRepertoireRevisionRequest\x1a,.repertoire.v1.GetRepertoireRevisionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_gen.repertoire.v1.repertoire_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETTRAININGTREEREQUEST']._serialized_start=58
  _globals['_GETTRAININGTREEREQUEST']._serialized_end=145
  _globals['_GETTRAININGTREERESPONSE']._serialized_start=147
  _globals['_GETTRAININGTREERESPONSE']._serialized_end=245
  _globals['_TRAININGLINE']._serialized_start=247
  _globals['_TRAININGLINE']._serialized_end=346
  _globals['_GETREPERTOIREREVISIONREQUEST']._serialized_start=348
  _globals['_GETREPERTOIREREVISIONREQUEST']._serialized_end=418
  _globals['_GETREPERTOIREREVISIONRESPONSE']._serialized_start=420
  _globals['_GETREPERTOIREREVISIONRESPONSE']._serialized_end=480
  _globals['_REPERTOIRESERVICE']._serialized_start=483
  _globals['_REPERTOIRESERVICE']._serialized_end=716
# @@protoc_insertion_point(module_scope)
