"""add email change code

Revision ID: 83b8cd0e1409
Revises: fc36dd8b9acf
Create Date: 2026-09-04 03:30:28.404669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b8cd0e1409'
down_revision: Union[str, Sequence[str], None] = 'fc36dd8b9acf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_codes',
    sa.Column('new_email', sa.String(length=254), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('code_hash', sa.LargeBinary(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_change_codes_new_email'), 'email_change_codes', ['new_email'], unique=False)
    op.create_index(op.f('ix_email_change_codes_user_id'), 'email_change_codes', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_email_change_codes_user_id'), table_name='email_change_codes')
    op.drop_index(op.f('ix_email_change_codes_new_email'), table_name='email_change_codes')
    op.drop_table('email_change_codes')
    # ### end Alembic commands ###
