"""update user model

Revision ID: 85f73991fac7
Revises: 83b8cd0e1409
Create Date: 2026-09-04 05:56:54.826886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85f73991fac7'
down_revision: Union[str, Sequence[str], None] = '83b8cd0e1409'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    gender = sa.Enum(
        'M',
        'F',
        name='gender',
    )
    gender.create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', gender, nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('bio', sa.String(length=75), nullable=True))
    op.add_column('users', sa.Column('telegram_alias', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'telegram_alias')
    op.drop_column('users', 'bio')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'country')
    op.drop_column('users', 'gender')
    # ### end Alembic commands ###
    gender = sa.Enum(
        'M',
        'F',
        name='gender'
    )
    gender.drop(op.get_bind())
